title: Dealer Listing API Documentation 
description: The basic usage of the dealer listing API. 
#theme: jekyll-theme-architect


- remote_theme: pages-themes/architect@v0.2.0
plugins:
-  jekyll-theme-architect # add this line to the plugins list if you already have one # add this line to the plugins list if you already have one